"""create users activities preferences tables

Revision ID: 602accf8adde
Revises: 
Create Date: 2026-04-30 10:16:26.449307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602accf8adde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_id', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('beta_user', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_rename', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_strava_id'), 'users', ['strava_id'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.BigInteger(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('generated_name', sa.String(), nullable=False),
    sa.Column('raw_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strava_activity_id')
    )
    op.create_index('ix_activities_user_created', 'activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), server_default='poetic', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index('ix_activities_user_created', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_strava_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
